### ISSUE TITLE
安安是谁？

### ISSUE THREAD

**Issue by SeifWu** [mengdaoshizhongxinyang/foraa#1]
`
if(answer === "不说"){
 console.log("🦙草泥马")
}
`

**Comment by mengdaoshizhongxinyang** [comment]
小学认识的朋友，你个傻狗

**Comment by wo877214096** [comment]
青梅竹马？

**Comment by SeifWu** [comment]
> 小学认识的朋友，你个傻狗

啧啧啧，渣男

**Comment by SeifWu** [comment]
> 青梅竹马？

两小无猜

**Comment by SeifWu** [comment]
![DB54D7FF79E405860616F57390338E82](https://user-images.githubusercontent.com/33513256/81542671-9e20e980-93a7-11ea-81a1-f42a60cc4c62.png)

**Comment by SeifWu** [comment]
![CA002D0F65C4548F85038B3BC18AC7F4](https://user-images.githubusercontent.com/33513256/81543016-1be4f500-93a8-11ea-9030-08ddb764b924.gif)
